{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osb-broker-go.fullname" . }}
  labels:
    {{- include "osb-broker-go.labels" . | nindent 4 }}
{{- end }}
